/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '浪费' at '17-5-9 下午8:31' with Gradle 2.11
 *
 * @author 浪费, @date 17-5-9 下午8:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
